<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        DB::unprepared(<<<'SQL'
            CREATE TABLE public.fcm_devices (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
                token TEXT NOT NULL UNIQUE,
                platform TEXT NOT NULL,
                registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE INDEX fcm_devices_user_id_index
            ON public.fcm_devices (user_id);

            ALTER TABLE public.fcm_devices ENABLE ROW LEVEL SECURITY;
            REVOKE ALL ON public.fcm_devices FROM anon, authenticated;

            CREATE OR REPLACE FUNCTION public.register_fcm_device(
                p_token TEXT,
                p_platform TEXT
            )
            RETURNS VOID
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = ''
            AS $$
            DECLARE
                current_user_id BIGINT := public.current_legacy_user_id();
            BEGIN
                IF current_user_id IS NULL THEN
                    RAISE EXCEPTION 'A signed-in user is required.';
                END IF;

                IF NULLIF(pg_catalog.btrim(p_token), '') IS NULL THEN
                    RAISE EXCEPTION 'A device token is required.';
                END IF;

                INSERT INTO public.fcm_devices (
                    user_id, token, platform, registered_at, last_seen_at
                )
                VALUES (
                    current_user_id,
                    pg_catalog.btrim(p_token),
                    pg_catalog.lower(pg_catalog.btrim(p_platform)),
                    NOW(),
                    NOW()
                )
                ON CONFLICT (token) DO UPDATE
                SET user_id = EXCLUDED.user_id,
                    platform = EXCLUDED.platform,
                    last_seen_at = NOW();
            END;
            $$;

            REVOKE ALL ON FUNCTION public.register_fcm_device(TEXT, TEXT) FROM PUBLIC;
            GRANT EXECUTE ON FUNCTION public.register_fcm_device(TEXT, TEXT) TO authenticated;

            CREATE OR REPLACE FUNCTION public.unregister_fcm_device(p_token TEXT)
            RETURNS VOID
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = ''
            AS $$
            BEGIN
                DELETE FROM public.fcm_devices
                WHERE user_id = public.current_legacy_user_id()
                  AND token = pg_catalog.btrim(p_token);
            END;
            $$;

            REVOKE ALL ON FUNCTION public.unregister_fcm_device(TEXT) FROM PUBLIC;
            GRANT EXECUTE ON FUNCTION public.unregister_fcm_device(TEXT) TO authenticated;

            CREATE TABLE public.fcm_notification_queue (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                notification_id BIGINT NOT NULL UNIQUE REFERENCES public.notifications(id) ON DELETE CASCADE,
                attempts INTEGER NOT NULL DEFAULT 0,
                last_error TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                sent_at TIMESTAMPTZ
            );

            REVOKE ALL ON public.fcm_notification_queue FROM anon, authenticated;

            CREATE OR REPLACE FUNCTION public.queue_fcm_notification()
            RETURNS TRIGGER
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = ''
            AS $$
            BEGIN
                INSERT INTO public.fcm_notification_queue (notification_id)
                VALUES (NEW.id)
                ON CONFLICT (notification_id) DO NOTHING;

                PERFORM pg_catalog.pg_notify('fcm_notifications', NEW.id::TEXT);

                RETURN NEW;
            END;
            $$;

            REVOKE ALL ON FUNCTION public.queue_fcm_notification() FROM PUBLIC;

            CREATE TRIGGER notifications_queue_fcm_delivery
            AFTER INSERT ON public.notifications
            FOR EACH ROW
            EXECUTE FUNCTION public.queue_fcm_notification();
            SQL);
    }

    public function down(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        DB::unprepared(<<<'SQL'
            DROP TRIGGER IF EXISTS notifications_queue_fcm_delivery
            ON public.notifications;
            DROP FUNCTION IF EXISTS public.queue_fcm_notification();
            DROP TABLE IF EXISTS public.fcm_notification_queue;
            DROP FUNCTION IF EXISTS public.unregister_fcm_device(TEXT);
            DROP FUNCTION IF EXISTS public.register_fcm_device(TEXT, TEXT);
            DROP TABLE IF EXISTS public.fcm_devices;
            SQL);
    }
};
